### ISSUE TITLE
Upgrade to newest python version

### ISSUE THREAD

**Issue by DurgNomis-drol** [joro75/Domoticz-Toyota-Plugin#61]
Hello, its me from the parent library. 
Would it be possible for you to upgrade to the newest python version 3.12 (3.11 or 3.10 would also be fine. This is so I don't need to support older python versions 😄

**Comment by joro75** [comment]
Hi @DurgNomis-drol,

I already suggested some changes to 'mytoyota', to not support Python 3.7 anymore. As a lot of the dependencies that are used by 'mytoyota' are also not supporting Python 3.7 anymore. 

Based on that, I checked if and when each version of Python was marked end-of-life. Please see the page: https://devguide.python.org/versions/

Python 3.7 is indeed not supported anymore, and Python 3.8 is still supported for less than a year. 
This at least makes it clear why a lot of other libraries are not supporting Python 3.7 anymore. 
I fully agree with stopping support for Python 3.7 in 'mytoyota', as it is also not supported by the Python organisation anymore.

This does give me some problems, as my internal home automation system is still using Python 3.7, so I do have to upgrade that, which also requires an operating system update. 

The problem that I forsee, is that when we require a very recent version of Python, this could be a burden for the end-users that have to update to a newer system and Python version. As the 'mytoyota' package is a library that is used by other programs, there could be valid reasons that the end-application is still using an older Python version. I therefor would like to propose that we support those Python versions that are supported by the Python organisation. As soon as a Python version is marked as 'end-of-life', we can also stop supporting it.

It should not be to difficult to still support Python 3.8 as all our dependencies are also still supporting Python 3.8. And that probably is because all those libraries have the same idea: we support what is still supported by the Python organisation.

Concluding: I thus would like to suggest to support Python 3.8 - Python 3.12, and stop supporting Python 3.8 on 2024-10.

**Comment by DurgNomis-drol** [comment]
Lets do that 🚀
